pipeline:
  node-build:
    image: node:latest
    commands:
      - npm ci
      - npm run build
      - docker cp /dist cicd_nginx_1:/usr/share/nginx/html

  show-echo:
    image: alpine
    commands:
      - echo "build success"
      - echo "good job"
      - echo "nice"