kind: pipeline
type: docker
name: Drone-Test

platform:
  os: linux
  arch: amd64

steps:
- name: node-build
  image: node:latest
  commands:
    - npm ci
    - npm run build

- name: show-echo
  image: alpine
  commands:
    - echo "build success"
    - echo "good job"
    - echo "nice"

services:
  hub:
    image: selenium/hub:3.13.0-argon
    ports:
      - "4444:4444"
 
  firefox:
    image: selenium/node-firefox:3.13.0-argon
    detach: true
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
 
  chrome:
    image: selenium/node-chrome:3.13.0-argon
    detach: true
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: hub
