kind: pipeline
type: docker
name: Drone-Test

platform:
  os: linux
  arch: amd64

steps:
- name: node-build
  image: node:latest
  environment:
    NODE_ENV: gh-pages
  commands:
    - npm ci
    - npm run build

- name: publish
  image: plugins/gh-pages
  pull: always
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    pages_directory: dist
trigger:
  branch:
    - master
