pipeline:
  node-build:
    image: node:latest
    environment:
      NODE_ENV: gh-pages
    commands:
      - npm ci
      - npm run build

  selenium_test:
    image: node:latest
    commands: 
      - npm run selenium_test

services:
  selenium:
   image: selenium/standalone-chrome

trigger:
  branch:
    - master
