pipeline:
  node-build:
    image: node:latest
    environment:
      NODE_ENV: deploy_ghpages
    commands:
      - npm ci
      - npm run build

  deploy_ghpages: 
    image: plugins/gh-pages
    settings:
      username:
        from_secret: username
      password:
        from_secret: password
      pages_directory: dist
      target_directory: temp

  selenium_test:
    image: node:latest
    networks:
      - drone-pipeline
    commands: 
      - npm run selenium_test

services:
  selenium-hub:
    image: selenium/hub
    networks:
     - drone-pipeline
    ports:
      - "4444:4444"
 
  firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub
 
  chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    volumes:
      - /dev/shm:/dev/shm
    environment:
      HUB_HOST: selenium-hub

trigger:
  branch:
    - master
